import { useMemo } from 'react';
import * as Yup from 'yup';

export const useGetDefaultValue = (edit: boolean, unitInfo: any, data: any) => {
  const {
    txbTagText,
    txbQtyText,
    locationID,
    orientationID,
    unitTypeID,
    ddlControlsPreferenceId,
    txbSummerSupplyAirCFMText,
    txbSummerReturnAirCFMText,
    txbSupplyAirESPText,
    txbExhaustAirESPText,
    unitModelID,
    unitVoltageID,
    txbAltitudeText,
    txbSummerOutdoorAirDBText,
    txbSummerOutdoorAirWBText,
    txbSummerOutdoorAirRHText,
    txbWinterOutdoorAirDBText,
    txbWinterOutdoorAirWBText,
    txbWinterOutdoorAirRHText,
    txbSummerReturnAirDBText,
    txbSummerReturnAirWBText,
    txbSummerReturnAirRHText,
    txbWinterReturnAirDBText,
    txbWinterReturnAirWBText,
    txbWinterReturnAirRHText,
    txbWinterPreheatSetpointDBText,
    txbSummerCoolingSetpointDBText,
    txbSummerCoolingSetpointWBText,
    txbWinterHeatingSetpointDBText,
    txbSummerReheatSetpointDBText,
    OA_FilterModelID,
    RA_FilterModelID,
    PreheatCompID,
    HeatExchCompID,
    CoolingCompID,
    HeatingCompID,
    txbOA_FilterPDText,
    txbRA_FilterPDText,
    ReheatCompID,
    DamperActuatorID,
    ElecHeaterVoltageID,
    PreheatElecHeaterInstallationID,
    HeatElecHeaterInstallationID,
    PreheatCoilHandingID,
    CoolingCoilHandingID,
    HeatingCoilHandingID,
    ddlValveTypeId,
    txbPreheatHWC_CapText,
    txbPreheatHWC_FlowRateText,
    txbCoolingCWC_CapText,
    txbCoolingCWC_FlowRateText,
    txbHeatingHWC_CapText,
    txbHeatingHWC_FlowRateText,
    txbReheatHWC_CapText,
    txbReheatHWC_FlowRateText,
    CoolingFluidTypeID,
    CoolingFluidConcentrationID,
    txbCoolingFluidEntTempText,
    txbCoolingFluidLvgTempText,
    txbRefrigSuctionTempText,
    txbRefrigLiquidTempText,
    txbRefrigSuperheatTempText,
    HeatingFluidTypeID,
    HeatingFluidConcentrationID,
    txbHeatingFluidEntTempText,
    txbHeatingFluidLvgTempText,
    txbRefrigCondensingTempText,
    txbRefrigVaporTempText,
    txbRefrigSubcoolingTempText,
    txbUnitHeightText,
    txbUnitLengthText,
    txbUnitWeightText,
    txbUnitWidthText,
    ddlHandingId,
    ddlSupplyAirOpeningId,
    ddlSupplyAirOpeningText,
    ddlExhaustAirOpeningId,
    ddlExhaustAirOpeningText,
    ddlOutdoorAirOpeningId,
    ddlOutdoorAirOpeningText,
    ddlReturnAirOpeningId,
    ddlReturnAirOpeningText,
  } = unitInfo;

  const defaultValues = useMemo(
    () => ({
      txtTag: edit ? txbTagText : '',
      txbQty: edit ? txbQtyText : 1,
      ddlLocationId: edit ? locationID : 1,
      ddlOrientationId: edit ? orientationID : 1,
      ddlUnitTypeId: edit ? unitTypeID : 1,
      ddlControlsPreferenceId: edit ? ddlControlsPreferenceId : 1,
      txbSummerSupplyAirCFM: edit ? txbSummerSupplyAirCFMText : 325,
      txbSummerReturnAirCFM: edit ? txbSummerReturnAirCFMText : 325,
      txbSupplyAirESP: edit ? txbSupplyAirESPText : 0.75,
      txbExhaustAirESP: edit ? txbExhaustAirESPText : 0.75,
      ddlUnitModelId: edit ? unitModelID : 1,
      ddlUnitVoltageId: edit ? unitVoltageID : 1,
      txbAltitude: txbAltitudeText || '',
      txbSummerOutdoorAirDB: txbSummerOutdoorAirDBText || '',
      txbSummerOutdoorAirWB: txbSummerOutdoorAirWBText || '',
      txbSummerOutdoorAirRH: txbSummerOutdoorAirRHText || '',
      txbWinterOutdoorAirDB: txbWinterOutdoorAirDBText || '',
      txbWinterOutdoorAirWB: txbWinterOutdoorAirWBText || '',
      txbWinterOutdoorAirRH: txbWinterOutdoorAirRHText || '',
      txbSummerReturnAirDB: txbSummerReturnAirDBText || '',
      txbSummerReturnAirWB: txbSummerReturnAirWBText || '',
      txbSummerReturnAirRH: txbSummerReturnAirRHText || '',
      txbWinterReturnAirDB: txbWinterReturnAirDBText || '',
      txbWinterReturnAirWB: txbWinterReturnAirWBText || '',
      txbWinterReturnAirRH: txbWinterReturnAirRHText || '',
      txbWinterPreheatSetpointDB: edit ? txbWinterPreheatSetpointDBText : 0,
      txbSummerCoolingSetpointDB: edit ? txbSummerCoolingSetpointDBText : 55,
      txbSummerCoolingSetpointWB: edit ? txbSummerCoolingSetpointWBText : 55,
      txbWinterHeatingSetpointDB: edit ? txbWinterHeatingSetpointDBText : 72,
      txbSummerReheatSetpointDB: edit ? txbSummerReheatSetpointDBText : 70,
      ddlOA_FilterModelId: edit ? OA_FilterModelID : 0,
      ddlRA_FilterModelId: edit ? RA_FilterModelID : 0,
      ddlPreheatCompId: edit ? PreheatCompID : 0,
      ddlHeatExchCompId: edit ? HeatExchCompID : 0,
      ddlCoolingCompId: edit ? CoolingCompID : 0,
      ddlHeatingCompId: edit ? HeatingCompID : 0,
      txbOA_FilterPD: edit ? txbOA_FilterPDText : 0.5,
      txbRA_FilterPD: edit ? txbRA_FilterPDText : 0.5,
      ddlReheatCompId: edit ? ReheatCompID : 0,
      ddlDamperAndActuatorId: edit ? DamperActuatorID : 0,
      ddlElecHeaterVoltageId: edit ? ElecHeaterVoltageID : 0,
      ddlPreheatElecHeaterInstallationId: edit ? PreheatElecHeaterInstallationID : 0,
      ddlHeatElecHeaterInstallationId: edit ? HeatElecHeaterInstallationID : 0,
      ddlPreheatCoilHandingId: edit ? PreheatCoilHandingID : 0,
      ddlCoolingCoilHandingId: edit ? CoolingCoilHandingID : 0,
      ddlHeatingCoilHandingId: edit ? HeatingCoilHandingID : 0,
      ddlValveTypeId: edit ? ddlValveTypeId : data?.valveType[0]?.id,
      txbPreheatHWC_Cap: edit ? txbPreheatHWC_CapText || 0 : 0,
      txbPreheatHWC_FlowRate: edit ? txbPreheatHWC_FlowRateText || 0 : 0,
      txbCoolingCWC_Cap: edit ? txbCoolingCWC_CapText || 0 : 0,
      txbCoolingCWC_FlowRate: edit ? txbCoolingCWC_FlowRateText || 0 : 0,
      txbHeatingHWC_Cap: edit ? txbHeatingHWC_CapText || 0 : 0,
      txbHeatingHWC_FlowRate: edit ? txbHeatingHWC_FlowRateText || 0 : 0,
      txbReheatHWC_Cap: edit ? txbReheatHWC_CapText || 0 : 0,
      txbReheatHWC_FlowRate: edit ? txbReheatHWC_FlowRateText || 0 : 0,
      ddlCoolingFluidTypeId: edit ? CoolingFluidTypeID : 0,
      ddlCoolingFluidConcentrationId: edit ? CoolingFluidConcentrationID : 0,
      txbCoolingFluidEntTemp: edit ? txbCoolingFluidEntTempText : 45,
      txbCoolingFluidLvgTemp: edit ? txbCoolingFluidLvgTempText : 55,
      txbRefrigSuctionTemp: edit ? txbRefrigSuctionTempText : 43,
      txbRefrigLiquidTemp: edit ? txbRefrigLiquidTempText : 77,
      txbRefrigSuperheatTemp: edit ? txbRefrigSuperheatTempText : 9,
      ddlHeatingFluidTypeId: edit ? HeatingFluidTypeID : 0,
      ddlHeatingFluidConcentrationId: edit ? HeatingFluidConcentrationID : 0,
      txbHeatingFluidEntTemp: edit ? txbHeatingFluidEntTempText : 140,
      txbHeatingFluidLvgTemp: edit ? txbHeatingFluidLvgTempText : 120,
      txbRefrigCondensingTemp: edit ? txbRefrigCondensingTempText : 115,
      txbRefrigVaporTemp: edit ? txbRefrigVaporTempText : 140,
      txbRefrigSubcoolingTemp: edit ? txbRefrigSubcoolingTempText : 5.4,
      txbPercentCondensingLoad: 100,
      txbUnitHeightText: edit ? txbUnitHeightText : 0,
      txbUnitLengthText: edit ? txbUnitLengthText : 0,
      txbUnitWeightText: edit ? txbUnitWeightText : 0,
      txbUnitWidthText: edit ? txbUnitWidthText : 0,
      ddlHandingId: edit ? ddlHandingId : 0,
      ddlSupplyAirOpeningId: edit ? ddlSupplyAirOpeningId : 0,
      ddlSupplyAirOpeningText: edit ? ddlSupplyAirOpeningText : '',
      ddlExhaustAirOpeningId: edit ? ddlExhaustAirOpeningId : 0,
      ddlExhaustAirOpeningText: edit ? ddlExhaustAirOpeningText : '',
      ddlOutdoorAirOpeningId: edit ? ddlOutdoorAirOpeningId : 0,
      ddlOutdoorAirOpeningText: edit ? ddlOutdoorAirOpeningText : '',
      ddlReturnAirOpeningId: edit ? ddlReturnAirOpeningId : 0,
      ddlReturnAirOpeningText: edit ? ddlReturnAirOpeningText : '',
      layoutImage: {},
    }),
    [
      data?.valveType,
      edit,
      CoolingCoilHandingID,
      CoolingCompID,
      CoolingFluidConcentrationID,
      CoolingFluidTypeID,
      DamperActuatorID,
      ElecHeaterVoltageID,
      HeatElecHeaterInstallationID,
      HeatExchCompID,
      HeatingCoilHandingID,
      HeatingCompID,
      HeatingFluidConcentrationID,
      HeatingFluidTypeID,
      OA_FilterModelID,
      PreheatCoilHandingID,
      PreheatCompID,
      PreheatElecHeaterInstallationID,
      RA_FilterModelID,
      ReheatCompID,
      ddlControlsPreferenceId,
      ddlExhaustAirOpeningId,
      ddlExhaustAirOpeningText,
      ddlHandingId,
      ddlOutdoorAirOpeningId,
      ddlOutdoorAirOpeningText,
      ddlReturnAirOpeningId,
      ddlReturnAirOpeningText,
      ddlSupplyAirOpeningId,
      ddlSupplyAirOpeningText,
      ddlValveTypeId,
      locationID,
      orientationID,
      txbAltitudeText,
      txbCoolingCWC_CapText,
      txbCoolingCWC_FlowRateText,
      txbCoolingFluidEntTempText,
      txbCoolingFluidLvgTempText,
      txbExhaustAirESPText,
      txbHeatingFluidEntTempText,
      txbHeatingFluidLvgTempText,
      txbHeatingHWC_CapText,
      txbHeatingHWC_FlowRateText,
      txbOA_FilterPDText,
      txbPreheatHWC_CapText,
      txbPreheatHWC_FlowRateText,
      txbQtyText,
      txbRA_FilterPDText,
      txbRefrigCondensingTempText,
      txbRefrigLiquidTempText,
      txbRefrigSubcoolingTempText,
      txbRefrigSuctionTempText,
      txbRefrigSuperheatTempText,
      txbRefrigVaporTempText,
      txbReheatHWC_CapText,
      txbReheatHWC_FlowRateText,
      txbSummerCoolingSetpointDBText,
      txbSummerCoolingSetpointWBText,
      txbSummerOutdoorAirDBText,
      txbSummerOutdoorAirRHText,
      txbSummerOutdoorAirWBText,
      txbSummerReheatSetpointDBText,
      txbSummerReturnAirCFMText,
      txbSummerReturnAirDBText,
      txbSummerReturnAirRHText,
      txbSummerReturnAirWBText,
      txbSummerSupplyAirCFMText,
      txbSupplyAirESPText,
      txbTagText,
      txbUnitHeightText,
      txbUnitLengthText,
      txbUnitWeightText,
      txbUnitWidthText,
      txbWinterHeatingSetpointDBText,
      txbWinterOutdoorAirDBText,
      txbWinterOutdoorAirRHText,
      txbWinterOutdoorAirWBText,
      txbWinterPreheatSetpointDBText,
      txbWinterReturnAirDBText,
      txbWinterReturnAirRHText,
      txbWinterReturnAirWBText,
      unitModelID,
      unitTypeID,
      unitVoltageID,
    ]
  );

  return defaultValues;
};

export const unitEditFormSchema = Yup.object().shape({
  txtTag: Yup.string().required('This field is required!'),
  txbQty: Yup.number().required('This field is required!'),
  ddlLocationId: Yup.number().required('This field is required!'),
  ddlOrientationId: Yup.number().required('This field is required!'),
  ddlUnitTypeId: Yup.number().required('This field is required!'),
  ddlControlsPreferenceId: Yup.number().required('This field is required!'),
  txbSummerSupplyAirCFM: Yup.number().required('This field is required!'),
  txbSummerReturnAirCFM: Yup.number().required('This field is required!'),
  txbSupplyAirESP: Yup.number().required('This field is required!'),
  txbExhaustAirESP: Yup.number().required('This field is required!'),
  ddlUnitModelId: Yup.number().required('This field is required!'),
  ddlUnitVoltageId: Yup.number().required('This field is required!'),
  txbWinterPreheatSetpointDB: Yup.number().required('This field is required!'),
  txbSummerCoolingSetpointDB: Yup.number().required('This field is required!'),
  txbSummerCoolingSetpointWB: Yup.number().required('This field is required!'),
  txbWinterHeatingSetpointDB: Yup.number().required('This field is required!'),
  txbSummerReheatSetpointDB: Yup.number().required('This field is required!'),
  ddlOA_FilterModelId: Yup.number().required('This field is required!'),
  ddlRA_FilterModelId: Yup.number().required('This field is required!'),
  ddlPreheatCompId: Yup.number().required('This field is required!'),
  ddlHeatExchCompId: Yup.number().required('This field is required!'),
  ddlCoolingCompId: Yup.number().required('This field is required!'),
  ddlHeatingCompId: Yup.number().required('This field is required!'),
  txbOA_FilterPD: Yup.number().required('This field is required!'),
  txbRA_FilterPD: Yup.number().required('This field is required!'),
  ddlReheatCompId: Yup.number().required('This field is required!'),
  ddlDamperAndActuatorId: Yup.number().required('This field is required!'),
  ddlElecHeaterVoltageId: Yup.number().required('This field is required!'),
  ddlPreheatElecHeaterInstallationId: Yup.number().required('This field is required!'),
  ddlHeatElecHeaterInstallationId: Yup.number().required('This field is required!'),
  ddlPreheatCoilHandingId: Yup.number().required('This field is required!'),
  ddlCoolingCoilHandingId: Yup.number().required('This field is required!'),
  ddlHeatingCoilHandingId: Yup.number().required('This field is required!'),
  ddlValveTypeId: Yup.number().required('This field is required!'),
  txbPreheatHWC_Cap: Yup.number(),
  txbPreheatHWC_FlowRate: Yup.number(),
  txbCoolingCWC_Cap: Yup.number(),
  txbCoolingCWC_FlowRate: Yup.number(),
  txbHeatingHWC_Cap: Yup.number(),
  txbHeatingHWC_FlowRate: Yup.number(),
  txbReheatHWC_Cap: Yup.number(),
  txbReheatHWC_FlowRate: Yup.number(),
  ddlCoolingFluidTypeId: Yup.number().required('This field is required!'),
  ddlCoolingFluidConcentrationId: Yup.number().required('This field is required!'),
  txbCoolingFluidEntTemp: Yup.number().required('This field is required!'),
  txbCoolingFluidLvgTemp: Yup.number().required('This field is required!'),
  txbRefrigSuctionTemp: Yup.number().required('This field is required!'),
  txbRefrigLiquidTemp: Yup.number().required('This field is required!'),
  txbRefrigSuperheatTemp: Yup.number().required('This field is required!'),
  ddlHeatingFluidTypeId: Yup.number().required('This field is required!'),
  ddlHeatingFluidConcentrationId: Yup.number().required('This field is required!'),
  txbHeatingFluidEntTemp: Yup.number().required('This field is required!'),
  txbHeatingFluidLvgTemp: Yup.number().required('This field is required!'),
  txbRefrigCondensingTemp: Yup.number().required('This field is required!'),
  txbRefrigVaporTemp: Yup.number().required('This field is required!'),
  txbRefrigSubcoolingTemp: Yup.number().required('This field is required!'),
  txbPercentCondensingLoad: Yup.number().required('This field is required!'),
  txbUnitHeightText: Yup.number().required('This field is required!'),
  txbUnitLengthText: Yup.number().required('This field is required!'),
  txbUnitWeightText: Yup.number().required('This field is required!'),
  txbUnitWidthText: Yup.number().required('This field is required!'),
  ddlHandingId: Yup.number().required('This field is required!'),
  ddlSupplyAirOpeningId: Yup.number(),
  ddlSupplyAirOpeningText: Yup.string(),
  ddlExhaustAirOpeningId: Yup.number(),
  ddlExhaustAirOpeningText: Yup.string(),
  ddlOutdoorAirOpeningId: Yup.number(),
  ddlOutdoorAirOpeningText: Yup.string(),
  ddlReturnAirOpeningId: Yup.number(),
  ddlReturnAirOpeningText: Yup.string(),
});
